services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: notification24-sql
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'YourStrong!Passw0rd'
    ports:
      - '1433:1433'
    healthcheck:
      test: ["CMD-SHELL", "bash -c '/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P YourStrong!Passw0rd -C -Q \"SELECT 1\"'"]
      interval: 10s
      timeout: 5s
      retries: 20

  rabbitmq:
    image: rabbitmq:3-management
    container_name: notification24-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - '5672:5672'
      - '15672:15672'
